on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  dir_listing:
    name: Create Directory Listing
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: 
      run: |
        cd images\blinkies\blinkies
        ls | jq -R -s -c 'split("\n")[:-1]' > index.json
        cd images\blinkies\blinkies
        ls | jq -R -s -c 'split("\n")[:-1]' > index.json
    - uses: EndBug/add-and-commit@v9
