name: Create Directory Listings

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  dir_listing:
    name: Create Directory Listing
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: 
      run: |
        sudo apt install tree
        cd images
        tree -J > index.json
    - uses: EndBug/add-and-commit@v9
